# Generated by Django 2.2.5 on 2019-09-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_gallery', models.FileField(upload_to='uploads/')),
                ('obj_file', models.FileField(upload_to='obj/')),
                ('mtl_file', models.FileField(upload_to='mtl/')),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
