# Generated by Django 2.2.5 on 2019-09-30 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0006_auto_20190930_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 17, 11, 49, 688729)),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='mtl_file',
            field=models.FileField(upload_to='mtl/', verbose_name='MTL soubor 3D modelu'),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='obj_file',
            field=models.FileField(upload_to='obj/', verbose_name='OBJ soubor 3D modelu'),
        ),
    ]
