# Generated by Django 2.2.5 on 2019-09-30 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0007_auto_20190930_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectmodel',
            name='name',
            field=models.CharField(default=None, max_length=500, verbose_name='Název 3D modelu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 17, 51, 27, 568584)),
        ),
    ]
