# Generated by Django 2.2.5 on 2019-10-02 13:53

import datetime
from django.db import migrations, models
import objectGallery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0008_auto_20190930_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 15, 53, 36, 593671)),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='image_gallery',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/', validators=[objectGallery.validators.validate_img_extension], verbose_name='Obrázky k modelu'),
        ),
    ]
