# Generated by Django 2.2.5 on 2019-10-16 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0012_auto_20191013_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 9, 41, 10, 311371)),
        ),
    ]
