# Generated by Django 2.2.5 on 2019-10-16 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0013_auto_20191016_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 14, 43, 13, 519989)),
        ),
    ]
