# Generated by Django 2.2.5 on 2019-11-06 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0014_auto_20191016_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(blank=True, default=None, null=True, upload_to='{id}/', verbose_name='Soubor k modelu')),
            ],
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 9, 46, 30, 597424)),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='image_gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectGallery.Files'),
        ),
    ]
