# Generated by Django 2.2.5 on 2019-11-06 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0015_auto_20191106_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectmodel',
            name='image_gallery',
        ),
        migrations.AddField(
            model_name='files',
            name='model_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='objectGallery.ObjectModel'),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 18, 57, 52, 605724)),
        ),
    ]
