# Generated by Django 2.2.5 on 2019-11-25 17:16

import datetime
from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0016_auto_20191106_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectmodel',
            name='thumb',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='thumbs/', verbose_name='Náhledový obrázek'),
        ),
        migrations.AlterField(
            model_name='files',
            name='f',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.bmp'], allowed_types=['image/jpeg', 'image/png', 'image/bmp'])], verbose_name='Soubor k modelu'),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 18, 16, 41, 9551)),
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='mtl_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mtl/', verbose_name='MTL soubor 3D modelu'),
        ),
    ]
