# Generated by Django 2.2.5 on 2019-11-27 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0017_auto_20191125_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 8, 58, 53, 779436)),
        ),
    ]
