# Generated by Django 2.2.5 on 2019-12-11 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0018_auto_20191127_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectmodel',
            name='tags',
        ),
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 8, 41, 4, 687264)),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('model_ids', models.ManyToManyField(to='objectGallery.ObjectModel')),
            ],
        ),
    ]
