# Generated by Django 2.2.5 on 2019-11-28 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectGallery', '0018_auto_20191127_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmodel',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 16, 52, 14, 573801)),
        ),
    ]
